version: '3.8'

services:
  db:
    image: postgres:12.0-alpine
    platform: linux/amd64
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_db
    ports:
      - 5434:5432

  redis:
    image: redis:7

volumes:
  postgres_data:
