version: '3.8'

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "your-email@example.com"
      PGADMIN_DEFAULT_PASSWORD: "your-secure-password"
    ports:
      - "127.0.0.1:5050:80"
    networks:
      - nginx_net

networks:
  nginx_net:
    external: true