services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/home/app/web
#      - ./backend/static_root:/home/app/web/static_root
#      - ./backend/media:/home/app/web/media
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=dreamers
    env_file:
      - ./backend/.env

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A project worker --loglevel=info
    volumes:
      - ./backend:/home/app/web
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - rabbitmq


volumes:
  postgres_data:
  static_volume:
  media_volume:
