version: '3.8'

services:
  web:
    container_name: web
    restart: always
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --workers 3 --log-level=info
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend/static_root:/home/app/web/static_root
      - ./backend/media:/home/app/web/media
    ports:
      - "8000:8000"
    expose:
      - 8000
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - nginx_net

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backups:/backups
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    env_file:
      - ./backend/.env
    networks:
      - nginx_net

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - nginx_net

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: celery -A project worker --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - nginx_net

  celery-beat:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: celery -A project beat --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - nginx_net

volumes:
  postgres_data:
  redis_data:

networks:
  nginx_net:
    name: nginx_net
    external: true
