version: '3.2'

services:
  db:
    image: postgres:13.0-alpine
    hostname: '0.0.0.0'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_HOST='0.0.0.0'
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_db
    ports:
      - 5432:5432


volumes:
  postgres_data: