version: '3.2'

services:
  db:
    image: postgres:13.0-alpine
    hostname: '0.0.0.0'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_HOST='0.0.0.0'
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_db
    ports:
      - 5433:5432

  backend:
    image: portal_backend
    user: root
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/ecommerce/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - default


volumes:
  postgres_data: