version: '3.7'

services:
  db:
    image: postgres:13.0-alpine
    hostname: '0.0.0.0'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_HOST='0.0.0.0'
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ecommerce_db
    ports:
      - 5433:5432
    networks:
      - proxynet

  backend:
    image: ecommerce-backend-image
    container_name: ecommerce-backend
    user: root
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/ecommerce/backend
    depends_on:
      - db
    networks:
      - proxynet


volumes:
  postgres_data:

networks:
  proxynet:
    name: custom_network
