# Generated by Django 4.0.8 on 2022-11-25 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPostStates',
            new_name='NewPostAreas',
        ),
        migrations.CreateModel(
            name='NewPostRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('description_ru', models.CharField(max_length=255)),
                ('description_translit', models.CharField(max_length=255)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostareas')),
            ],
        ),
        migrations.CreateModel(
            name='NewPostCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=255)),
                ('settlement_type', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=18)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=18)),
                ('description', models.CharField(max_length=255)),
                ('description_ru', models.CharField(max_length=255)),
                ('description_translit', models.CharField(max_length=255)),
                ('settlement_type_description', models.CharField(max_length=255)),
                ('settlement_type_description_ru', models.CharField(max_length=255)),
                ('settlement_type_description_translit', models.CharField(max_length=255)),
                ('warehouse', models.BooleanField(default=False)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostregion')),
            ],
        ),
    ]
