# Generated by Django 4.0.8 on 2022-11-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0003_newpostdepartments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpostdepartments',
            name='receiving_limitations_on_dimensions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='newpostdepartments',
            name='schedule',
            field=models.JSONField(default=dict),
        ),
    ]
