# Generated by Django 4.0.8 on 2022-11-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0004_alter_newpostdepartments_receiving_limitations_on_dimensions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpostdepartments',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
