# Generated by Django 4.0.8 on 2022-11-30 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0005_newpostdepartments_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpostdepartments',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='newpost.newpostcities'),
        ),
    ]
