# Generated by Django 4.0.8 on 2023-02-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0006_alter_newpostdepartments_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpostdepartments',
            name='ref',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
