# Generated by Django 4.0.8 on 2023-02-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0007_newpostdepartments_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpostareas',
            name='id',
        ),
        migrations.RemoveField(
            model_name='newpostcities',
            name='id',
        ),
        migrations.RemoveField(
            model_name='newpostdepartments',
            name='id',
        ),
        migrations.AlterField(
            model_name='newpostareas',
            name='ref',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newpostcities',
            name='ref',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='newpostdepartments',
            name='ref',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
