# Generated by Django 4.2.3 on 2024-08-10 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
            ],
            options={
                'verbose_name': 'Интерьер',
                'verbose_name_plural': '1. Интерьеры',
            },
        ),
        migrations.CreateModel(
            name='InteriorLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('interior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layers', to='interior.interior')),
            ],
            options={
                'verbose_name': 'Слой интерьера',
                'verbose_name_plural': '2. Слои интерьера',
            },
        ),
        migrations.CreateModel(
            name='InteriorLayerMaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_groups', to='interior.interiorlayer')),
                ('material_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interior_layers_groups', to='material.materialgroups')),
            ],
            options={
                'verbose_name': 'Группа материалов интерьера',
                'verbose_name_plural': '3. Группы материалов интерьера',
            },
        ),
        migrations.CreateModel(
            name='InteriorMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.color')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='interior.interiorlayermaterialgroup')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.material')),
            ],
            options={
                'verbose_name': 'Материал слоя',
                'verbose_name_plural': '4. Материалы слоя',
            },
        ),
    ]
