# Generated by Django 4.0.10 on 2023-10-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0015_remove_attributegroup_category'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_groups', to='attribute.attributegroup')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_groups', to='category.category')),
            ],
            options={
                'verbose_name': 'Category Attribute Group',
                'verbose_name_plural': 'Category Attribute Groups',
                'ordering': ['order'],
                'unique_together': {('category', 'attribute_group')},
            },
        ),
    ]
