# Generated by Django 4.2.3 on 2024-11-17 18:01

import apps.abstract.fields.fields_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='collection',
            name='image',
            field=apps.abstract.fields.fields_image.DeletableImageField(blank=True, null=True, upload_to=''),
        ),
    ]
