# Generated by Django 4.0.10 on 2023-10-21 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0015_remove_attributegroup_category'),
        ('category', '0002_categoryattributegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryattributegroup',
            name='attribute_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attribute_groups', to='attribute.attributegroup'),
        ),
    ]
