# Generated by Django 4.0.10 on 2024-02-04 18:26

import apps.abstract.fields.fields_image
import apps.attribute.abstract.fields
import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('type', apps.attribute.abstract.fields.AttributeGroupTypeField(choices=[('text', 'Text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('float', 'Float'), ('color', 'Color'), ('range', 'Range'), ('image', 'Image')], default='text', max_length=24, verbose_name='Type')),
                ('custom', models.BooleanField(default=False)),
                ('price_required', models.CharField(blank=True, choices=[('sub_group', 'Цена на подгруппу'), ('attribute', 'Цена на каждую единицу'), ('multiplier', 'multiplier'), ('sub_group_multiplier', 'sub_group_multiplier')], default=None, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Группа атрибутов',
            },
        ),
        migrations.CreateModel(
            name='AttributeGroupUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeUnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float')], default='string', max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_group', to='attribute.attributegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='attribute.attributegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attribute.attributegroupunit'),
        ),
        migrations.CreateModel(
            name='AttributeColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='attribute.attributegroup')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_colors', to='material.color')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Text')),
                ('value_integer', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Integer')),
                ('value_boolean', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Boolean')),
                ('value_float', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Float')),
                ('value_color_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Color')),
                ('value_color_hex', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=7, null=True, samples=None, verbose_name='Color HEX')),
                ('value_color_image', apps.abstract.fields.fields_image.DeletableImageField(blank=True, null=True, upload_to='', verbose_name='Color IMAGE')),
                ('value_image_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('value_image_image', apps.abstract.fields.fields_image.DeletableImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Image')),
                ('value_min', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Min')),
                ('value_max', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Max')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('manual', models.BooleanField(default=False)),
                ('price', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='attribute.attributegroup')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='attribute.attributecolor')),
                ('sub_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='attribute.attributesubgroup')),
            ],
            options={
                'ordering': ['sub_group', 'value_text', 'value_integer', 'value_boolean', 'value_float', 'value_color_hex', 'value_min', 'value_max', 'value_image_name'],
                'abstract': False,
                'unique_together': {('attribute_group', 'value_boolean'), ('attribute_group', 'value_color_name', 'value_color_hex', 'value_color_image'), ('attribute_group', 'value_integer'), ('attribute_group', 'value_min', 'value_max'), ('attribute_group', 'value_text'), ('attribute_group', 'value_float')},
            },
        ),
        migrations.CreateModel(
            name='AttributeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_str', models.SlugField(blank=True, null=True)),
                ('value_int', models.PositiveIntegerField(blank=True, null=True)),
                ('value_float', models.FloatField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attribute.attribute')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='attribute.attributeunitgroup')),
            ],
            options={
                'ordering': ('attribute', 'value_str', 'value_int', 'value_float'),
                'unique_together': {('unit', 'attribute'), ('unit', 'attribute', 'value_int'), ('unit', 'attribute', 'value_float')},
            },
        ),
    ]
