# Generated by Django 4.0.7 on 2022-11-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributesubgroup',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
