# Generated by Django 4.0.7 on 2022-09-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_alter_attribute_value_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='attributegroup',
            name='price_required',
            field=models.CharField(blank=True, choices=[('sub_group', 'sub_group'), ('attribute', 'attribute')], default=None, max_length=9, null=True),
        ),
    ]
