# Generated by Django 4.0.7 on 2022-11-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_attributesubgroup_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributegroup',
            name='price_required',
            field=models.CharField(blank=True, choices=[('sub_group', 'sub_group'), ('attribute', 'attribute'), ('multiplier', 'multiplier')], default=None, max_length=10, null=True),
        ),
    ]
