# Generated by Django 4.0 on 2022-08-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('attribute', '0002_attributegroup_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributegroup',
            name='predefined_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.attributegroup'),
        ),
        migrations.CreateModel(
            name='PredefinedOptionsGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_groups', to='category.category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attributegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
