# Generated by Django 4.0 on 2022-08-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_attributegroup_predefined_group_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredefinedOptionsGroups',
        ),
    ]
