# Generated by Django 4.0.7 on 2022-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_attribute_price_attributegroup_price_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='group',
            new_name='attribute_group',
        ),
        migrations.AlterField(
            model_name='attributeunitgroup',
            name='type',
            field=models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float')], default='string', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('attribute_group', 'value_min', 'value_max'), ('attribute_group', 'value_text'), ('attribute_group', 'value_boolean'), ('attribute_group', 'value_integer'), ('attribute_group', 'value_color_name', 'value_color_hex', 'value_color_image'), ('attribute_group', 'value_float')},
        ),
    ]
