# Generated by Django 4.0 on 2022-08-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_remove_attributegroup_predefined_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedoptionsgroups',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
