# Generated by Django 4.0.7 on 2022-11-17 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0005_alter_attributegroup_price_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributesubgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='attribute.attributegroup'),
        ),
    ]
