# Generated by Django 4.0 on 2022-08-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('attribute', '0006_predefinedoptionsgroups_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedoptionsgroups',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_option_groups', to='category.category'),
        ),
        migrations.CreateModel(
            name='PredefinedAttributeGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('required', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_attribute_groups', to='category.category')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attributegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
