# Generated by Django 4.0 on 2022-08-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0007_alter_predefinedoptionsgroups_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedattributegroups',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
