# Generated by Django 4.0.8 on 2022-12-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0007_colors_attributecolor_attribute_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='rgb',
            field=models.JSONField(default=list),
        ),
    ]
