# Generated by Django 4.0 on 2022-08-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0008_alter_predefinedattributegroups_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedoptionsgroups',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
