# Generated by Django 4.0.8 on 2022-12-05 16:47

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0008_colors_rgb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='hex',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None),
        ),
    ]
