# Generated by Django 4.0 on 2022-08-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0009_alter_predefinedoptionsgroups_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedattributegroups',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='predefinedoptionsgroups',
            name='custom',
            field=models.BooleanField(default=False),
        ),
    ]
