# Generated by Django 4.0.8 on 2022-12-05 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0009_alter_colors_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attribute.attributecolor'),
        ),
    ]
