# Generated by Django 4.0.8 on 2022-12-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0010_alter_attribute_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ('value_text', 'value_integer', 'value_boolean', 'value_float', 'value_color_hex', 'value_min', 'value_max', 'value_image_name')},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributes', to='attribute.attributecolor'),
        ),
    ]
