# Generated by Django 4.0 on 2022-08-03 14:50

import apps.attribute.abstract.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0010_predefinedattributegroups_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedattributegroups',
            name='type',
            field=apps.attribute.abstract.fields.OptionGroupField(choices=[('attribute', 'Attribute'), ('text', 'Text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('float', 'Float'), ('color', 'Color'), ('range', 'Range'), ('image', 'Image')], default='attribute', max_length=24, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='predefinedoptionsgroups',
            name='type',
            field=apps.attribute.abstract.fields.OptionGroupField(choices=[('attribute', 'Attribute'), ('text', 'Text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('float', 'Float'), ('color', 'Color'), ('range', 'Range'), ('image', 'Image')], default='attribute', max_length=24, verbose_name='Type'),
        ),
    ]
