# Generated by Django 4.0.8 on 2022-12-06 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0011_alter_attribute_options_alter_attribute_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributecolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_colors', to='attribute.colors'),
        ),
    ]
