# Generated by Django 4.0 on 2022-08-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0011_predefinedattributegroups_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predefinedattributegroups',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='predefinedoptionsgroups',
            name='custom',
        ),
    ]
