# Generated by Django 4.0.10 on 2023-10-20 14:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0012_alter_attributecolor_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='value_color_base_hex',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=7, null=True, samples=None, verbose_name='Base Color HEX'),
        ),
    ]
