# Generated by Django 4.0 on 2022-08-03 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0012_remove_predefinedattributegroups_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predefinedattributegroups',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attribute.attributegroupunit'),
        ),
        migrations.AddField(
            model_name='predefinedoptionsgroups',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attribute.attributegroupunit'),
        ),
        migrations.AlterField(
            model_name='predefinedattributegroups',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.attributegroup'),
        ),
        migrations.AlterField(
            model_name='predefinedoptionsgroups',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.attributegroup'),
        ),
    ]
