# Generated by Django 4.0.10 on 2023-10-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0013_attribute_value_color_base_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='value_color_base_hex',
        ),
    ]
