# Generated by Django 4.0 on 2022-08-04 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0013_predefinedattributegroups_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributegroup',
            name='required',
        ),
    ]
