# Generated by Django 4.0.10 on 2023-10-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0014_remove_attribute_value_color_base_hex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributegroup',
            name='category',
        ),
    ]
