# Generated by Django 4.0.10 on 2023-11-21 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0015_remove_attributegroup_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributegroup',
            options={'verbose_name': 'Группа атрибутов'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attributes', to='attribute.attributesubgroup'),
        ),
        migrations.AlterField(
            model_name='attributegroup',
            name='price_required',
            field=models.CharField(blank=True, choices=[('sub_group', 'Цена на подгруппу'), ('attribute', 'Цена на каждую единицу'), ('multiplier', 'multiplier'), ('sub_group_multiplier', 'sub_group_multiplier')], default=None, max_length=20, null=True),
        ),
    ]
