# Generated by Django 4.0.10 on 2023-11-21 17:40

import apps.abstract.fields.fields_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0016_alter_attributegroup_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='value_color_image',
            field=apps.abstract.fields.fields_image.DeletableImageField(blank=True, null=True, upload_to='', verbose_name='Color IMAGE'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='value_image_image',
            field=apps.abstract.fields.fields_image.DeletableImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
