# Generated by Django 4.0.10 on 2023-11-21 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0017_alter_attribute_value_color_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['sub_group', 'value_text', 'value_integer', 'value_boolean', 'value_float', 'value_color_hex', 'value_min', 'value_max', 'value_image_name']},
        ),
    ]
