# Generated by Django 4.0.10 on 2023-12-12 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('attribute', '0018_alter_attribute_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributecolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_colors', to='material.color'),
        ),
        migrations.DeleteModel(
            name='Colors',
        ),
    ]
