# Generated by Django 4.0.10 on 2024-01-09 16:49

import apps.abstract.fields.fields_attributes
import apps.abstract.fields.fields_image
import apps.attribute.abstract.fields
import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('product', '0001_initial'), ('product', '0002_alter_productattribute_options_and_more'), ('product', '0003_productoptionpricemultiplier'), ('product', '0004_alter_productoptionpricemultiplier_option_group'), ('product', '0005_remove_productclassoptiongroup_quantity'), ('product', '0006_alter_productoptionpricemultiplier_product'), ('product', '0007_alter_productclassoption_options'), ('product', '0008_alter_productclassoption_value_attribute'), ('product', '0009_productclass_depth_step_and_more'), ('product', '0010_productclassoptiongroup_d_productclassoptiongroup_h_and_more'), ('product', '0011_productclass_max_initial_price_and_more'), ('product', '0012_productclassproductattributegroups_use_all_attributes'), ('product', '0013_alter_productclassproductattributegroups_use_all_attributes'), ('product', '0014_productclassoption_price_and_more'), ('product', '0015_rename_price_required_productclassoptiongroup_option_price_required_and_more'), ('product', '0016_productclass_generate_variants_from_sizes'), ('product', '0017_product_depth_product_height_product_width'), ('product', '0018_remove_product_name_remove_product_slug'), ('product', '0019_rename_min_initial_price_productclass_initial_price_and_more'), ('product', '0020_productclass_square_decimeter_price_and_more'), ('product', '0021_alter_product_options_productclass3dblendermodel'), ('product', '0022_alter_productclassoption_value_color_image_and_more'), ('product', '0023_productclassoptiongroup_attribute_sub_group'), ('product', '0024_productpartmaterial_productpartmaterials_and_more'), ('product', '0025_productpartcolors'), ('product', '0026_delete_productpartcolors'), ('product', '0027_productpartcolor'), ('product', '0028_rename_productpartmaterial_productpart'), ('product', '0029_remove_productpartmaterials_sub_group'), ('product', '0030_productpartmaterials_color_and_more'), ('product', '0031_remove_skumaterials_group_and_more'), ('product', '0032_remove_product3dblendermodel_blend_and_more'), ('product', '0033_productpartmaterials_code'), ('product', '0034_alter_productpartmaterials_code'), ('product', '0035_alter_sku_code'), ('product', '0036_alter_skumaterials_sku_alter_skuoptions_sku_and_more'), ('product', '0037_productpartmaterialsgroups_area'), ('product', '0038_remove_productpartmaterialsgroups_area_and_more'), ('product', '0039_alter_productpart_area'), ('product', '0040_alter_productpart_area'), ('product', '0041_productpartmaterialsgroups_add_palette'), ('product', '0042_alter_productpartmaterialsgroups_add_palette'), ('product', '0043_alter_skumaterials_material'), ('product', '0044_productpartmaterials_show_in_catalogue'), ('product', '0045_alter_productpartmaterials_options_alter_sku_options_and_more'), ('product', '0046_remove_skuimages_image_thumb_alter_skuimages_image'), ('product', '0047_alter_skuimages_sku'), ('product', '0048_skuimages_image_thumbnails'), ('product', '0049_alter_sku_managers_skuimages_local')]

    dependencies = [
        ('attribute', '0001_initial'),
        ('material', '0001_initial'),
        ('attribute', '0012_alter_attributecolor_color'),
        ('attribute', '0015_remove_attributegroup_category'),
        ('material', '0009_remove_material_color_materialgroups_type_and_more'),
        ('material', '0016_blendermaterial_ao'),
        ('material', '0012_blendermaterial_remove_material_bump_and_more'),
        ('material', '0024_alter_palettecolor_color_alter_palettecolor_palette'),
        ('attribute', '0018_alter_attribute_options'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock')),
                ('render_variants', models.BooleanField(default=False)),
                ('generate_sku', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('generate_sku_from_options', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('depth_step', models.PositiveIntegerField(blank=True, null=True, verbose_name='Depth step')),
                ('generate_products_from_dimensions', models.BooleanField(default=False)),
                ('height_step', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height step')),
                ('max_depth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max depth')),
                ('max_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max height')),
                ('max_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max width')),
                ('min_depth', models.PositiveIntegerField(default=0, verbose_name='Depth')),
                ('min_height', models.PositiveIntegerField(default=0, verbose_name='Height')),
                ('min_width', models.PositiveIntegerField(default=0, verbose_name='Width')),
                ('width_step', models.PositiveIntegerField(blank=True, null=True, verbose_name='Width step')),
                ('initial_price', models.PositiveIntegerField(default=0, verbose_name='Initial price')),
                ('generate_variants_from_sizes', models.BooleanField(default=False)),
                ('square_decimeter_price', models.PositiveIntegerField(default=0, verbose_name='Square decimeter price')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductClassProductAttributeGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_product_attributes', to='attribute.attributegroup')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes_groups', to='product.productclass')),
                ('use_all_attributes', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=1024, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='product.product')),
            ],
            options={
                'ordering': ['-materials__material__show_in_catalogue', 'images'],
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClassProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_class_attributes', to='attribute.attribute')),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.productclassproductattributegroups')),
            ],
            options={
                'unique_together': {('attribute_group', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ProductClassOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('type', apps.attribute.abstract.fields.OptionGroupField(choices=[('attribute', 'Attribute'), ('text', 'Text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('float', 'Float'), ('color', 'Color'), ('range', 'Range'), ('image', 'Image')], default='attribute', max_length=24, verbose_name='Type')),
                ('use_all_options', models.BooleanField(default=False)),
                ('image_dependency', models.BooleanField(default=False)),
                ('model_3d_name', models.CharField(blank=True, max_length=255, null=True)),
                ('attribute_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_class_option_group', to='attribute.attributegroup')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='product.productclass')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attribute.attributegroupunit')),
                ('d', models.BooleanField(default=False)),
                ('h', models.BooleanField(default=False)),
                ('w', models.BooleanField(default=False)),
                ('mlt', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('option_price_required', models.BooleanField(default=False)),
                ('attribute_sub_group', models.ManyToManyField(blank=True, to='attribute.attributesubgroup')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('product_class', 'name', 'attribute_group')},
            },
        ),
        migrations.CreateModel(
            name='ProductClassOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Text')),
                ('value_integer', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Integer')),
                ('value_boolean', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Boolean')),
                ('value_float', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Float')),
                ('value_color_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Color')),
                ('value_color_hex', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=7, null=True, samples=None, verbose_name='Color HEX')),
                ('value_color_image', apps.abstract.fields.fields_image.DeletableImageField(blank=True, null=True, upload_to='', verbose_name='Color IMAGE')),
                ('value_image_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('value_image_image', apps.abstract.fields.fields_image.DeletableImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Image')),
                ('value_min', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Min')),
                ('value_max', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Max')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.productclassoptiongroup')),
                ('value_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_class_options', to='attribute.attribute')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('value_attribute', 'value_text', 'value_integer', 'value_boolean', 'value_float', 'value_color_hex', 'value_min', 'value_max', 'value_image_name'),
                'abstract': False,
                'unique_together': {('attribute_group', 'value_integer'), ('attribute_group', 'value_min', 'value_max'), ('attribute_group', 'value_text'), ('attribute_group', 'value_color_name', 'value_color_hex', 'value_color_image'), ('attribute_group', 'value_attribute'), ('attribute_group', 'value_float'), ('attribute_group', 'value_boolean')},
            },
        ),
        migrations.CreateModel(
            name='ProductClassAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_attributes', to='attribute.attributegroup')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.productclass')),
                ('value_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attribute.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Product3DBlenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtl', apps.abstract.fields.fields_attributes.CustomFileField(blank=True, null=True, storage=apps.abstract.fields.fields_attributes.OverwriteStorage, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mtl'])])),
                ('obj', apps.abstract.fields.fields_attributes.CustomFileField(blank=True, null=True, storage=apps.abstract.fields.fields_attributes.OverwriteStorage, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['obj'])])),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_3d', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productclass'),
        ),
        migrations.CreateModel(
            name='SkuOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productclassoption')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.sku')),
            ],
            options={
                'ordering': ('sku', 'option'),
                'unique_together': {('sku', 'option')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='product.productclassproductattributes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.product')),
            ],
            options={
                'ordering': ('attribute__attribute_group',),
                'unique_together': {('product', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ProductOptionPriceMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplier', to='product.productclassoptiongroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Width'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['width', 'height', 'depth']},
        ),
        migrations.CreateModel(
            name='ProductClass3DBlenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blend', apps.abstract.fields.fields_attributes.CustomFileField(storage=apps.abstract.fields.fields_attributes.OverwriteStorage, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['blend'])])),
                ('product_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_3d', to='product.productclass')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blender_name', models.CharField(max_length=255)),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='product.productclass')),
                ('area', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Площадь, м2')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPartMaterialsGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_groups', to='material.materialgroups')),
                ('product_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_groups', to='product.productpartmaterial')),
                ('add_palette', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.palette')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPartMaterialsSubGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='product.productpartmaterialsgroups')),
                ('product_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_sub_groups', to='product.productpartmaterial')),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_sub_groups', to='material.materialsubgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPartMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='product.productpartmaterialsgroups')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_class_materials', to='material.material')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_parts', to='material.color')),
                ('code', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('show_in_catalogue', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-show_in_catalogue'],
            },
        ),
        migrations.CreateModel(
            name='ProductStaticPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blender_name', models.CharField(max_length=255)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_class_static_color', to='material.color')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.materialgroups')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_class_static_materials', to='material.material')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_parts', to='product.productclass')),
            ],
        ),
        migrations.CreateModel(
            name='SkuMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_materials', to='product.productpartmaterials')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='product.sku')),
            ],
            options={
                'ordering': ['-material__show_in_catalogue'],
            },
        ),
        migrations.AlterModelManagers(
            name='sku',
            managers=[
            ],
        ),
        migrations.CreateModel(
            name='SkuImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.abstract.fields.fields_image.DeletableImageField(upload_to='')),
                ('index', models.PositiveIntegerField(default=0)),
                ('sku', models.ForeignKey(max_length=1024, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.sku')),
                ('image_thumbnails', models.JSONField(blank=True, default=dict)),
                ('local', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
    ]
