# Generated by Django 4.0.10 on 2024-02-04 18:26

import apps.abstract.fields.fields_attributes
import apps.abstract.fields.fields_image
import apps.attribute.abstract.fields
import colorfield.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attribute', '0001_initial'),
        ('category', '0001_initial'),
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='Price')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock')),
                ('render_variants', models.BooleanField(default=False)),
                ('generate_sku', models.BooleanField(default=False)),
                ('width', models.PositiveIntegerField(blank=True, default=0, verbose_name='Width')),
                ('height', models.PositiveIntegerField(blank=True, default=0, verbose_name='Height')),
                ('depth', models.PositiveIntegerField(blank=True, default=0, verbose_name='Depth')),
                ('remove_images', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['width', 'height', 'depth'],
            },
        ),
        migrations.CreateModel(
            name='ProductClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('min_width', models.PositiveIntegerField(default=0, verbose_name='Width')),
                ('max_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max width')),
                ('width_step', models.PositiveIntegerField(blank=True, null=True, verbose_name='Width step')),
                ('min_height', models.PositiveIntegerField(default=0, verbose_name='Height')),
                ('max_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max height')),
                ('height_step', models.PositiveIntegerField(blank=True, null=True, verbose_name='Height step')),
                ('min_depth', models.PositiveIntegerField(default=0, verbose_name='Depth')),
                ('max_depth', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max depth')),
                ('depth_step', models.PositiveIntegerField(blank=True, null=True, verbose_name='Depth step')),
                ('initial_price', models.PositiveIntegerField(default=0, verbose_name='Initial price')),
                ('square_decimeter_price', models.PositiveIntegerField(default=0, verbose_name='Square decimeter price')),
                ('generate_sku_from_options', models.BooleanField(default=False, verbose_name='Сгенерировать Sku и сочетания цветов')),
                ('generate_variants_from_sizes', models.BooleanField(default=False, verbose_name='Сгенерировать варианты из размеров')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.category')),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='category.collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductClassOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('type', apps.attribute.abstract.fields.OptionGroupField(choices=[('attribute', 'Attribute'), ('text', 'Text'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('float', 'Float'), ('color', 'Color'), ('range', 'Range'), ('image', 'Image')], default='attribute', max_length=24, verbose_name='Type')),
                ('model_3d_name', models.CharField(blank=True, max_length=255, null=True)),
                ('w', models.BooleanField(default=False)),
                ('h', models.BooleanField(default=False)),
                ('d', models.BooleanField(default=False)),
                ('mlt', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('use_all_options', models.BooleanField(default=False)),
                ('option_price_required', models.BooleanField(default=False)),
                ('image_dependency', models.BooleanField(default=False)),
                ('attribute_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_class_option_group', to='attribute.attributegroup')),
                ('attribute_sub_group', models.ManyToManyField(blank=True, to='attribute.attributesubgroup')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_groups', to='product.productclass')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attribute.attributegroupunit')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('product_class', 'name', 'attribute_group')},
            },
        ),
        migrations.CreateModel(
            name='ProductClassProductAttributeGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_all_attributes', models.BooleanField(default=True)),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_product_attributes', to='attribute.attributegroup')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes_groups', to='product.productclass')),
            ],
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=1024, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='product.product')),
            ],
            options={
                'ordering': ['code'],
            },
            managers=[
                ('objects_no_distinct', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SkuMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_materials', to='material.productpartmaterials')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='product.sku')),
            ],
        ),
        migrations.CreateModel(
            name='SkuImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.abstract.fields.fields_image.DeletableImageField(upload_to='')),
                ('image_thumbnails', models.JSONField(blank=True, default=dict)),
                ('index', models.PositiveIntegerField(default=0)),
                ('local', models.BooleanField(default=False)),
                ('sku', models.ForeignKey(max_length=1024, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.sku')),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOptionPriceMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplier', to='product.productclassoptiongroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multipliers', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/')),
                ('image_thumb', models.ImageField(blank=True, null=True, upload_to='product/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClassProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_class_attributes', to='attribute.attribute')),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.productclassproductattributegroups')),
            ],
            options={
                'unique_together': {('attribute_group', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='ProductClassOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Text')),
                ('value_integer', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Integer')),
                ('value_boolean', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Boolean')),
                ('value_float', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Float')),
                ('value_color_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Color')),
                ('value_color_hex', colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=7, null=True, samples=None, verbose_name='Color HEX')),
                ('value_color_image', apps.abstract.fields.fields_image.DeletableImageField(blank=True, null=True, upload_to='', verbose_name='Color IMAGE')),
                ('value_image_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('value_image_image', apps.abstract.fields.fields_image.DeletableImageField(blank=True, max_length=500, null=True, upload_to='', verbose_name='Image')),
                ('value_min', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Min')),
                ('value_max', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Max')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.productclassoptiongroup')),
                ('value_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_class_options', to='attribute.attribute')),
            ],
            options={
                'ordering': ('value_attribute', 'value_text', 'value_integer', 'value_boolean', 'value_float', 'value_color_hex', 'value_min', 'value_max', 'value_image_name'),
                'abstract': False,
                'unique_together': {('attribute_group', 'value_boolean'), ('attribute_group', 'value_color_name', 'value_color_hex', 'value_color_image'), ('attribute_group', 'value_integer'), ('attribute_group', 'value_attribute'), ('attribute_group', 'value_min', 'value_max'), ('attribute_group', 'value_text'), ('attribute_group', 'value_float')},
            },
        ),
        migrations.CreateModel(
            name='ProductClassMaterialSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materials_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.materialsset')),
                ('product_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materials_set', to='product.productclass')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClassAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_attributes', to='attribute.attributegroup')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.productclass')),
                ('value_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attribute.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='ProductClass3DBlenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blend', apps.abstract.fields.fields_attributes.CustomFileField(storage=apps.abstract.fields.fields_attributes.OverwriteStorage, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['blend'])])),
                ('product_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_3d', to='product.productclass')),
            ],
        ),
        migrations.CreateModel(
            name='Product3DBlenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='')),
                ('mtl', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_3d', to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.productclass'),
        ),
        migrations.CreateModel(
            name='Lights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=1000)),
                ('pos_x', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pos_y', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pos_z', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('model_3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lights', to='product.product3dblendermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CameraLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_x', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('pos_y', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('pos_z', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('rad_x', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('rad_y', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('rad_z', models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20)),
                ('model_3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='product.product3dblendermodel')),
            ],
        ),
        migrations.CreateModel(
            name='SkuOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productclassoption')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.sku')),
            ],
            options={
                'ordering': ('sku', 'option'),
                'unique_together': {('sku', 'option')},
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='product.productclassproductattributes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.product')),
            ],
            options={
                'ordering': ('attribute__attribute_group',),
                'unique_together': {('product', 'attribute')},
            },
        ),
    ]
