# Generated by Django 4.0.7 on 2022-11-17 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ('attribute__attribute_group',)},
        ),
        migrations.AddField(
            model_name='productclassoptiongroup',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productclassproductattributegroups',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes_groups', to='product.productclass'),
        ),
    ]
