# Generated by Django 4.0.10 on 2024-01-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={},
        ),
    ]
