# Generated by Django 4.0.10 on 2024-01-19 17:12

import apps.abstract.fields.fields_image
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_sku_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelManagers(
            name='sku',
            managers=[
                ('objects_no_distinct', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='product3dblendermodel',
            name='mtl',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product3dblendermodel',
            name='obj',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
    ]
