# Generated by Django 4.0.10 on 2024-01-15 22:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_sku_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['-materials__material__show_in_catalogue', 'images']},
        ),
        migrations.AlterModelManagers(
            name='sku',
            managers=[
                ('objects_no_distinct', django.db.models.manager.Manager()),
            ],
        ),
    ]
