# Generated by Django 4.0.7 on 2022-09-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productattribute_value_color_hex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skuoptions',
            options={'ordering': ('sku', 'option__group')},
        ),
        migrations.AlterUniqueTogether(
            name='skuoptions',
            unique_together={('sku', 'option')},
        ),
        migrations.RemoveField(
            model_name='skuoptions',
            name='option_group',
        ),
    ]
