# Generated by Django 4.0.7 on 2022-11-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductOptionPriceMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productclassoptiongroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
