# Generated by Django 4.0.10 on 2024-02-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('product', '0002_productclass_materials_set_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomizedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.DecimalField(decimal_places=1, default=1, max_digits=10)),
                ('price', models.DecimalField(decimal_places=1, default=1, max_digits=10)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='material.productpart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customized_parts', to='product.product')),
            ],
        ),
    ]
