# Generated by Django 4.0.7 on 2022-09-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_skuoptions_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclassoptiongroup',
            name='image_dependency',
            field=models.BooleanField(default=False),
        ),
    ]
