# Generated by Django 4.0.10 on 2024-02-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productcustomizedpart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcustomizedpart',
            name='price',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
