# Generated by Django 4.0 on 2022-08-03 11:00

import apps.attribute.abstract.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
        ('product', '0003_skuoption_alter_skuoptions_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClassOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=500, null=True, verbose_name='Text')),
                ('value_integer', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Integer')),
                ('value_boolean', models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Boolean')),
                ('value_float', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Float')),
                ('value_color_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Color')),
                ('value_color_hex', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color HEX')),
                ('value_color_image', apps.attribute.abstract.fields.AttributeImageField(blank=True, null=True, storage=apps.attribute.abstract.fields.OverwriteStorage, upload_to='', verbose_name='Color IMAGE')),
                ('value_image_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Name')),
                ('value_image_image', apps.attribute.abstract.fields.AttributeImageField(blank=True, max_length=500, null=True, storage=apps.attribute.abstract.fields.OverwriteStorage, upload_to='', verbose_name='Image')),
                ('value_min', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Min')),
                ('value_max', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Max')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productclassoptiongroup')),
                ('value_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='attribute.attribute')),
            ],
            options={
                'ordering': ('value_attribute', 'value_text', 'value_integer', 'value_boolean', 'value_float', 'value_color_name', 'value_min', 'value_max', 'value_image_name'),
                'unique_together': {('group', 'value_float'), ('group', 'value_text'), ('group', 'value_min', 'value_max'), ('group', 'value_boolean'), ('group', 'value_color_name', 'value_color_hex', 'value_color_image'), ('group', 'value_attribute'), ('group', 'value_integer')},
            },
        ),
        migrations.CreateModel(
            name='SkuOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productclassoption')),
                ('option_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.productclassoptiongroup')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.sku')),
            ],
            options={
                'ordering': ('sku', 'option'),
                'unique_together': {('sku', 'option')},
            },
        ),
        migrations.RenameModel(
            old_name='SkuOptionImage',
            new_name='ProductAttributeOptionImage',
        ),
        migrations.DeleteModel(
            name='SkuOption',
        ),
        migrations.AlterField(
            model_name='productattributeoptionimage',
            name='product_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productclassoption'),
        ),
    ]
