# Generated by Django 4.0.7 on 2022-11-17 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productoptionpricemultiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoptionpricemultiplier',
            name='option_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multiplier', to='product.productclassoptiongroup'),
        ),
    ]
