# Generated by Django 4.0 on 2022-08-03 11:34

import apps.attribute.abstract.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0002_attributegroup_custom'),
        ('product', '0004_productclassoption_skuoptions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'ordering': ('value_attribute', 'value_text', 'value_integer', 'value_boolean', 'value_float', 'value_color_name', 'value_min', 'value_max', 'value_image_name')},
        ),
        migrations.RenameField(
            model_name='productattribute',
            old_name='attribute',
            new_name='value_attribute',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attribute.attributegroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productattribute',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_boolean',
            field=models.BooleanField(blank=True, db_index=True, null=True, verbose_name='Boolean'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_color_hex',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Color HEX'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_color_image',
            field=apps.attribute.abstract.fields.AttributeImageField(blank=True, null=True, storage=apps.attribute.abstract.fields.OverwriteStorage, upload_to='', verbose_name='Color IMAGE'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_color_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_float',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='Float'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_image_image',
            field=apps.attribute.abstract.fields.AttributeImageField(blank=True, max_length=500, null=True, storage=apps.attribute.abstract.fields.OverwriteStorage, upload_to='', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_image_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_integer',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Integer'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_max',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Max'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_min',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Min'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='value_text',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Text'),
        ),
        migrations.AlterUniqueTogether(
            name='productattribute',
            unique_together={('group', 'value_integer'), ('group', 'value_boolean'), ('group', 'value_text'), ('group', 'value_attribute'), ('group', 'value_color_name', 'value_color_hex', 'value_color_image'), ('group', 'value_min', 'value_max'), ('group', 'value_float')},
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='attribute_group',
        ),
    ]
