# Generated by Django 4.0.10 on 2024-02-20 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productcustomizedpart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product3dblendermodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_3d', to='product.product'),
        ),
    ]
