# Generated by Django 4.0.10 on 2024-01-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_cameralocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.IntegerField(default=1000)),
                ('pos_x', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pos_y', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('pos_q', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('model_3d', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product3dblendermodel')),
            ],
        ),
    ]
