# Generated by Django 4.0.7 on 2022-09-23 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_attribute_price_attributegroup_price_required'),
        ('product', '0004_productclassoptiongroup_image_dependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductClassProductAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_product_attributes', to='attribute.attributegroup')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attributes', to='product.productclass')),
            ],
        ),
    ]
