# Generated by Django 4.0 on 2022-08-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclassoptiongroup',
            name='save_all_options',
            field=models.BooleanField(default=False),
        ),
    ]
