# Generated by Django 4.0.10 on 2024-01-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_lights'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cameralocations',
            old_name='pos_q',
            new_name='pos_z',
        ),
        migrations.RenameField(
            model_name='lights',
            old_name='pos_q',
            new_name='pos_z',
        ),
    ]
