# Generated by Django 4.0.10 on 2024-02-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product3dblendermodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='generate_sku',
            field=models.BooleanField(default=False, verbose_name='Сгенерировать SKU из материалов'),
        ),
    ]
