# Generated by Django 4.0.10 on 2024-01-26 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_pos_q_cameralocations_pos_z_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameralocations',
            name='model_3d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='product.product3dblendermodel'),
        ),
        migrations.AlterField(
            model_name='lights',
            name='model_3d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lights', to='product.product3dblendermodel'),
        ),
    ]
