# Generated by Django 4.0.7 on 2022-09-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_attribute_price_attributegroup_price_required'),
        ('product', '0006_productclassattributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclassattributes',
            name='attribute_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class', to='attribute.attributegroup'),
        ),
        migrations.AlterField(
            model_name='productclassattributes',
            name='product_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='product.productclass'),
        ),
    ]
