# Generated by Django 4.0.8 on 2022-12-06 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0012_alter_attributecolor_color'),
        ('product', '0007_alter_productclassoption_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productclassoption',
            name='value_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_class_options', to='attribute.attribute'),
        ),
    ]
