# Generated by Django 4.0.10 on 2024-02-23 20:45

import apps.abstract.fields.fields_image
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('product', '0007_alter_product_generate_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPartScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='product.cameralocations')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.productpart')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPartSceneMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', apps.abstract.fields.fields_image.DeletableImageField(upload_to='')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_scene', to='material.productpartmaterials')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_scene', to='product.productpartscene')),
            ],
        ),
    ]
