# Generated by Django 4.0.10 on 2024-01-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_cameralocations_model_3d_alter_lights_model_3d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameralocations',
            name='pos_x',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cameralocations',
            name='pos_y',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cameralocations',
            name='pos_z',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cameralocations',
            name='rad_x',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cameralocations',
            name='rad_y',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cameralocations',
            name='rad_z',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20),
        ),
    ]
