# Generated by Django 4.0.7 on 2022-09-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_attribute_price_attributegroup_price_required'),
        ('product', '0007_alter_productclassattributes_attribute_group_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productclassoptiongroup',
            unique_together={('product_class', 'name', 'attribute_group')},
        ),
    ]
