# Generated by Django 4.0.10 on 2024-01-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_cameralocations_pos_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productclass',
            name='generate_products_from_dimensions',
        ),
        migrations.AddField(
            model_name='product',
            name='remove_images',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='generate_sku_from_options',
            field=models.BooleanField(default=False, verbose_name='Сгенерировать Sku и сочетания цветов'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='generate_variants_from_sizes',
            field=models.BooleanField(default=False, verbose_name='Сгенерировать варианты из размеров'),
        ),
    ]
