# Generated by Django 4.0.10 on 2023-10-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productclassoption_value_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='depth_step',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Depth step'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='generate_products_from_dimensions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productclass',
            name='height_step',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Height step'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='max_depth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='max_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max height'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='max_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max width'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='min_depth',
            field=models.PositiveIntegerField(default=0, verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='min_height',
            field=models.PositiveIntegerField(default=0, verbose_name='Min height'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='min_width',
            field=models.PositiveIntegerField(default=0, verbose_name='Min width'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='width_step',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Width step'),
        ),
    ]
