# Generated by Django 4.0.10 on 2024-01-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_sku_options_alter_sku_managers'),
        ('product', '0009_remove_productclass_generate_products_from_dimensions_and_more'),
    ]

    operations = [
    ]
