# Generated by Django 4.0.10 on 2024-01-29 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_merge_20240128_1426'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['code']},
        ),
    ]
