# Generated by Django 4.0.10 on 2024-02-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productpartscenematerial_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='images_by_sku',
            field=models.BooleanField(default=False),
        ),
    ]
