# Generated by Django 4.0.10 on 2023-10-21 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productclassoptiongroup_d_productclassoptiongroup_h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='max_initial_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max price'),
        ),
        migrations.AddField(
            model_name='productclass',
            name='min_initial_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='productclassoptiongroup',
            name='mlt',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
