# Generated by Django 4.2.3 on 2024-06-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productclass_images_by_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['width', 'height', 'depth'], 'verbose_name': 'Вариант', 'verbose_name_plural': '2. Варианты'},
        ),
        migrations.AlterModelOptions(
            name='product3dblendermodel',
            options={'verbose_name': '3D модель', 'verbose_name_plural': '3D модели'},
        ),
        migrations.AlterModelOptions(
            name='productclass',
            options={'ordering': ['name'], 'verbose_name': 'Товар', 'verbose_name_plural': '1. Товары'},
        ),
        migrations.AlterField(
            model_name='productclass',
            name='depth_step',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Шаг глубины'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='height_step',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Шаг высоты'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='initial_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Стартовая цена'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='max_depth',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. глубина'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='max_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс высота'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='max_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. ширина'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='min_depth',
            field=models.PositiveIntegerField(default=0, verbose_name='Глубина'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='min_height',
            field=models.PositiveIntegerField(default=0, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='min_width',
            field=models.PositiveIntegerField(default=0, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='square_decimeter_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена за м2'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='width_step',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Шаг ширины'),
        ),
    ]
