# Generated by Django 4.0.10 on 2023-11-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productclass_max_initial_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclassproductattributegroups',
            name='use_all_attributes',
            field=models.BooleanField(default=False),
        ),
    ]
