# Generated by Django 4.2.3 on 2024-08-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_cameralocations_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpartscenematerialimage',
            name='image_thumbnails',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
