# Generated by Django 4.0.10 on 2023-11-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productclassoption_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productclassoptiongroup',
            old_name='price_required',
            new_name='option_price_required',
        ),
        migrations.RenameField(
            model_name='productclassoptiongroup',
            old_name='save_all_options',
            new_name='use_all_options',
        ),
        migrations.AlterField(
            model_name='productclassoption',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
