# Generated by Django 4.2.3 on 2024-08-10 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
        ('product', '0014_productpartscenematerialimage_image_thumbnails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='interior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='interior.interior'),
        ),
    ]
