# Generated by Django 4.0.10 on 2023-11-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_price_required_productclassoptiongroup_option_price_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='generate_variants_from_sizes',
            field=models.BooleanField(default=False),
        ),
    ]
