# Generated by Django 4.0.10 on 2023-11-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productclass_generate_variants_from_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Depth'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Width'),
        ),
    ]
