# Generated by Django 4.2.3 on 2024-08-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interior', '0001_initial'),
        ('product', '0016_cameralocationsinteriorlayer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CameraLocationsInteriorLayer',
            new_name='CameraInteriorLayer',
        ),
        migrations.RenameModel(
            old_name='CameraLocationsInteriorLayerMaterial',
            new_name='CameraInteriorLayerMaterial',
        ),
        migrations.RenameModel(
            old_name='CameraLocationsInteriorLayerMaterialGroup',
            new_name='CameraInteriorLayerMaterialGroup',
        ),
        migrations.RenameModel(
            old_name='CameraLocationsInteriorLayerMaterialImage',
            new_name='CameraInteriorLayerMaterialImage',
        ),
    ]
