# Generated by Django 4.2.3 on 2024-09-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_rename_cameralocationsinteriorlayer_camerainteriorlayer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product3dblendermodel',
            name='eye_level',
            field=models.DecimalField(decimal_places=4, default=1.5, max_digits=20),
        ),
        migrations.AddField(
            model_name='product3dblendermodel',
            name='fov_degrees',
            field=models.DecimalField(decimal_places=4, default=30, max_digits=20),
        ),
        migrations.AddField(
            model_name='product3dblendermodel',
            name='render_from_eye_level',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product3dblendermodel',
            name='steps',
            field=models.IntegerField(default=5),
        ),
    ]
