# Generated by Django 4.0.10 on 2023-11-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_product_depth_product_height_product_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
