# Generated by Django 4.0.10 on 2023-11-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_product_name_remove_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productclass',
            old_name='min_initial_price',
            new_name='initial_price',
        ),
        migrations.RemoveField(
            model_name='productclass',
            name='max_initial_price',
        ),
    ]
