# Generated by Django 4.0.10 on 2023-11-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_min_initial_price_productclass_initial_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='square_decimeter_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Square decimeter price'),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='initial_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Initial price'),
        ),
    ]
