# Generated by Django 4.2.3 on 2024-10-22 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_blendermaterial_aspect_ratio'),
        ('product', '0020_alter_product3dblendermodel_eye_level'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skuoptions',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skuoptions',
            name='option',
        ),
        migrations.RemoveField(
            model_name='skuoptions',
            name='sku',
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={},
        ),
        migrations.AlterModelManagers(
            name='sku',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='sku',
            name='materials',
            field=models.ManyToManyField(related_name='sku_materials', to='material.productpartmaterials'),
        ),
        migrations.DeleteModel(
            name='SkuMaterials',
        ),
        migrations.DeleteModel(
            name='SkuOptions',
        ),
    ]
