# Generated by Django 4.0.10 on 2023-11-13 11:12

import apps.abstract.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_productclass_square_decimeter_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['width', 'height', 'depth']},
        ),
        migrations.CreateModel(
            name='ProductClass3DBlenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blend', apps.abstract.fields.CustomFileField(storage=apps.abstract.fields.OverwriteStorage, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['blend'])])),
                ('product_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_3d', to='product.productclass')),
            ],
        ),
    ]
