# Generated by Django 4.2.3 on 2024-10-22 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_skuoptions_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='generate_sku',
            new_name='generate_sku_from_materials',
        ),
    ]
