# Generated by Django 4.2.3 on 2024-10-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_rename_generate_sku_product_generate_sku_from_materials'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuimages',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku_images', to='product.camera'),
        ),
    ]
