# Generated by Django 4.2.3 on 2024-10-22 18:01

import apps.abstract.fields.fields_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_skuimages_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuimages',
            name='image',
            field=apps.abstract.fields.fields_image.DeletableImageField(blank=True, null=True, upload_to=''),
        ),
    ]
