# Generated by Django 4.0.10 on 2023-12-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
        ('product', '0023_productclassoptiongroup_attribute_sub_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPartMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blender_name', models.CharField(max_length=255)),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='product.productclass')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPartMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPartMaterialsGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_groups', to='material.materialgroups')),
                ('product_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_groups', to='product.productpartmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPartMaterialsSubGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_groups', to='product.productpartmaterialsgroups')),
                ('product_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_sub_groups', to='product.productpartmaterial')),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_sub_groups', to='material.materialsubgroup')),
            ],
        ),
        migrations.CreateModel(
            name='SkuMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productpartmaterialsgroups')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productpartmaterials')),
                ('sub_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productpartmaterialssubgroups')),
            ],
        ),
        migrations.AddField(
            model_name='productpartmaterials',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='product.productpartmaterialsgroups'),
        ),
        migrations.AddField(
            model_name='productpartmaterials',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_class_materials', to='material.material'),
        ),
        migrations.AddField(
            model_name='productpartmaterials',
            name='sub_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='product.productpartmaterialssubgroups'),
        ),
    ]
