# Generated by Django 4.0.10 on 2023-12-20 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_remove_material_color_materialgroups_type_and_more'),
        ('product', '0024_productpartmaterial_productpartmaterials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPartColors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parts', to='material.color')),
                ('product_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.productpartmaterial')),
            ],
        ),
    ]
