# Generated by Django 4.0.10 on 2023-12-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productpartcolors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPartColors',
        ),
    ]
