# Generated by Django 4.2.3 on 2024-10-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_sku_generate_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product3dblendermodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_3d', to='product.product'),
        ),
    ]
