# Generated by Django 4.0.10 on 2023-12-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_blendermaterial_remove_material_bump_and_more'),
        ('product', '0026_delete_productpartcolors'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPartColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_parts', to='material.color')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='product.productpartmaterialsgroups')),
            ],
        ),
    ]
