# Generated by Django 4.2.3 on 2024-11-17 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_product3dblendermodel_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='number_in_collection',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productclass',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
