# Generated by Django 4.2.3 on 2024-12-07 18:13

import apps.abstract.fields.fields_image
from django.db import migrations
import project.storage


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_productclass_number_in_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpartscenematerialimage',
            name='image',
            field=apps.abstract.fields.fields_image.DeletableImageField(max_length=1024, storage=project.storage.S3Storage, upload_to=''),
        ),
    ]
