# Generated by Django 4.0.10 on 2023-12-20 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_rename_productpartmaterial_productpart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpartmaterials',
            name='sub_group',
        ),
    ]
