# Generated by Django 4.2.3 on 2024-12-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_alter_productpartscenematerialimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='productclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
