# Generated by Django 4.0.10 on 2023-12-21 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_blendermaterial_remove_material_bump_and_more'),
        ('product', '0029_remove_productpartmaterials_sub_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpartmaterials',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_parts', to='material.color'),
        ),
        migrations.AlterField(
            model_name='productpartmaterials',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_class_materials', to='material.material'),
        ),
        migrations.DeleteModel(
            name='ProductPartColor',
        ),
    ]
