# Generated by Django 4.0.10 on 2023-12-21 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_productpartmaterials_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skumaterials',
            name='group',
        ),
        migrations.RemoveField(
            model_name='skumaterials',
            name='sub_group',
        ),
        migrations.AddField(
            model_name='skumaterials',
            name='sku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.sku'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skuoptions',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='product.sku'),
        ),
    ]
