# Generated by Django 4.2.3 on 2025-01-29 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_productclass_created_at_productclass_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productclass',
            options={'ordering': ['-created_at', 'name'], 'verbose_name': 'Товар', 'verbose_name_plural': '1. Товары'},
        ),
    ]
