# Generated by Django 4.0.10 on 2023-12-25 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_skumaterials_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product3dblendermodel',
            name='blend',
        ),
        migrations.RemoveField(
            model_name='product3dblendermodel',
            name='blend1',
        ),
    ]
