# Generated by Django 4.2.3 on 2025-01-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_alter_productclass_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcustomizedpart',
            name='area',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productcustomizedpart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
