# Generated by Django 4.2.3 on 2025-01-29 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_alter_materialgroups_price_and_more'),
        ('product', '0032_alter_productcustomizedpart_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCustomizedPartMaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Цена, м2')),
                ('material_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.materialgroups')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcustomizedpart')),
            ],
        ),
    ]
