# Generated by Django 4.0.10 on 2023-12-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_remove_product3dblendermodel_blend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpartmaterials',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
