# Generated by Django 4.2.3 on 2025-01-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_productcustomizedpartmaterialgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcustomizedpartmaterialgroup',
            name='group_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена, группы за м2'),
        ),
        migrations.AlterField(
            model_name='productcustomizedpartmaterialgroup',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена'),
        ),
    ]
