# Generated by Django 4.0.10 on 2023-12-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_productpartmaterials_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpartmaterials',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
