# Generated by Django 4.0.10 on 2023-12-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_productpartmaterials_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='code',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
