# Generated by Django 4.2.3 on 2025-02-19 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_alter_productcustomizedpartmaterialgroup_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product3dblendermodel',
            name='eye_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
