# Generated by Django 4.0.10 on 2023-12-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0016_blendermaterial_ao'),
        ('product', '0035_alter_sku_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skumaterials',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='product.sku'),
        ),
        migrations.AlterField(
            model_name='skuoptions',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.sku'),
        ),
        migrations.CreateModel(
            name='ProductStaticPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blender_name', models.CharField(max_length=255)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_class_static_color', to='material.color')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.materialgroups')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_class_static_materials', to='material.material')),
                ('product_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='static_parts', to='product.productclass')),
            ],
        ),
    ]
