# Generated by Django 4.0.10 on 2023-12-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_skumaterials_sku_alter_skuoptions_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpartmaterialsgroups',
            name='area',
            field=models.IntegerField(default=0),
        ),
    ]
