# Generated by Django 4.2.3 on 2025-03-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_alter_product3dblendermodel_eye_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='product.product'),
        ),
    ]
