# Generated by Django 4.0.10 on 2023-12-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_productpartmaterialsgroups_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpartmaterialsgroups',
            name='area',
        ),
        migrations.AddField(
            model_name='productpart',
            name='area',
            field=models.IntegerField(default=0),
        ),
    ]
