# Generated by Django 4.0.10 on 2023-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_alter_productpart_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpart',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Площадь, м2'),
        ),
    ]
