# Generated by Django 4.0.10 on 2023-12-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0024_alter_palettecolor_color_alter_palettecolor_palette'),
        ('product', '0041_productpartmaterialsgroups_add_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpartmaterialsgroups',
            name='add_palette',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.palette'),
        ),
    ]
