# Generated by Django 4.0.10 on 2023-12-28 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_alter_productpartmaterialsgroups_add_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skumaterials',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sku_materials', to='product.productpartmaterials'),
        ),
    ]
