# Generated by Django 4.0.10 on 2023-12-29 23:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_productpartmaterials_show_in_catalogue'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpartmaterials',
            options={'ordering': ['-show_in_catalogue']},
        ),
        migrations.AlterModelOptions(
            name='sku',
            options={'ordering': ['-materials__material__show_in_catalogue', 'images']},
        ),
        migrations.AlterModelOptions(
            name='skumaterials',
            options={'ordering': ['-material__show_in_catalogue']},
        ),
        migrations.AlterModelManagers(
            name='sku',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
