# Generated by Django 4.0.10 on 2023-12-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_remove_skuimages_image_thumb_alter_skuimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skuimages',
            name='sku',
            field=models.ForeignKey(max_length=1024, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.sku'),
        ),
    ]
