# Generated by Django 4.0.10 on 2023-12-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0047_alter_skuimages_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='skuimages',
            name='image_thumbnails',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
