# Generated by Django 4.0.10 on 2024-01-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_skuimages_image_thumbnails'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sku',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='skuimages',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
