from .admin_product_class import ProductClassAdmin
from .admin_product_class_attribues import ProductClassAttributesInline
from .admin_product_class_options import ProductClassOptionInline, ProductClassOptionGroupAdmin, \
    ProductClassOptionGroupInline, ProductClassOptionGroupCustomInline
from .admin_product_class_product_attributes import ProductClassProductAttributeGroupsInline, \
    ProductClassProductAttributesInline, ProductClassProductAttributeGroupsAdmin
