# Generated by Django 4.0.8 on 2022-12-12 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newpost', '0006_alter_newpostdepartments_city'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[(0, 'Адресная доставка'), (1, 'Новая почта')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='OrderNewPostDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newpost.newpostdepartments')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='newpost', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAddressDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='order.order')),
            ],
        ),
    ]
