# Generated by Django 4.0.8 on 2022-12-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productclassoption_value_attribute'),
        ('order', '0002_order_delivery_type_orderproduct_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('0', 'Адресная доставка'), ('1', 'Новая почта')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_product_sku', to='product.sku'),
        ),
    ]
