# Generated by Django 4.0.8 on 2022-12-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_delivery_type_alter_orderproduct_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddressdelivery',
            name='apartment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderaddressdelivery',
            name='entrance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderaddressdelivery',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
