# Generated by Django 4.0.8 on 2023-02-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderaddressdelivery_apartment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderaddressdelivery',
            options={'verbose_name': 'Адресная доставка', 'verbose_name_plural': 'Адресная доставка'},
        ),
        migrations.AlterModelOptions(
            name='ordernewpostdelivery',
            options={'verbose_name': 'Доставка Новой Почтой', 'verbose_name_plural': 'Доставка Новой Почтой'},
        ),
    ]
