# Generated by Django 4.0.10 on 2023-12-12 21:11

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('hex', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None)),
                ('rgb', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.materialgroups')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('nrm', models.FileField(upload_to='')),
                ('col', models.FileField(blank=True, null=True, upload_to='')),
                ('bump', models.FileField(blank=True, null=True, upload_to='')),
                ('bump16', models.FileField(blank=True, null=True, upload_to='')),
                ('disp', models.FileField(blank=True, null=True, upload_to='')),
                ('disp16', models.FileField(blank=True, null=True, upload_to='')),
                ('rgh', models.FileField(blank=True, null=True, upload_to='')),
                ('mtl', models.FileField(blank=True, null=True, upload_to='')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.color')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='material.materialgroups')),
                ('sub_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='material.materialsubgroup')),
            ],
        ),
    ]
