# Generated by Django 4.0.10 on 2024-01-15 19:16

import apps.abstract.fields.fields_image
from django.db import migrations, models
import django.db.models.deletion
import project.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('hex', models.CharField(max_length=7)),
                ('rgb', models.JSONField(blank=True, default=list)),
                ('lvl', models.PositiveIntegerField(default=0)),
                ('index', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['index', 'lvl'],
            },
        ),
        migrations.CreateModel(
            name='BlenderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('col', apps.abstract.fields.fields_image.DeletableFileField(storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Color')),
                ('nrm_gl', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Norma GL')),
                ('nrm_dx', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Norma DX')),
                ('bump', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Bump')),
                ('bump16', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Bump 16 bit')),
                ('disp', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Displacement')),
                ('disp16', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Displacement 16 bit')),
                ('rgh', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Roughness')),
                ('mtl', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Metalness')),
                ('refl', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Reflection')),
                ('ao', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='', verbose_name='Ambient Occlusion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('ral', models.CharField(blank=True, max_length=24, null=True)),
                ('hex', models.CharField(max_length=7)),
                ('rgb', models.JSONField(blank=True, default=list)),
                ('lvl', models.PositiveIntegerField(default=0)),
                ('mid_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.basecolor')),
            ],
            options={
                'ordering': ['ral'],
            },
        ),
        migrations.CreateModel(
            name='MaterialGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('material', 'material'), ('color', 'color')], default='material', max_length=25)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена, м2')),
                ('price_level', models.CharField(blank=True, choices=[('group', 'Цена на группу'), ('sub_group', 'Цена на суб группу'), ('material', 'Цена на материал')], max_length=9, null=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialSubGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена, м2')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.materialgroups')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('image', apps.abstract.fields.fields_image.DeletableImageField(blank=True, null=True, storage=project.storage.CustomFileSystemStorage, upload_to='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена, м2')),
                ('blender_material', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material', to='material.blendermaterial')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='material.materialgroups')),
                ('sub_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='material.materialsubgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaletteColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='material.color')),
                ('palette', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='material.palette')),
            ],
            options={
                'unique_together': {('palette', 'color')},
            },
        ),
    ]
