# Generated by Django 4.0.10 on 2023-12-20 10:27

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('hex', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=7, samples=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='color',
            name='ral',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='color',
            name='mid_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.midcolor'),
        ),
    ]
