# Generated by Django 4.0.10 on 2024-01-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['mid_color__index']},
        ),
        migrations.AddField(
            model_name='color',
            name='rgb_real',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
