# Generated by Django 4.2.3 on 2024-08-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecolor',
            options={'ordering': ['index', 'lvl'], 'verbose_name': 'Базовый цвет', 'verbose_name_plural': 'Базовые цвета'},
        ),
        migrations.AlterModelOptions(
            name='blendermaterial',
            options={'verbose_name': 'Материал Blender', 'verbose_name_plural': '5. Материалы Blender'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['mid_color__lvl', 'mid_color__index'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('group', 'sub_group', 'name'), 'verbose_name': 'Материал', 'verbose_name_plural': '4. Материалы'},
        ),
        migrations.AlterModelOptions(
            name='materialgroups',
            options={'ordering': ('name',), 'verbose_name': 'Группа материалов', 'verbose_name_plural': '2. Группы материалов'},
        ),
        migrations.AlterModelOptions(
            name='materialsset',
            options={'verbose_name': 'Набор материалов', 'verbose_name_plural': '1. Наборы материалов'},
        ),
        migrations.AlterModelOptions(
            name='materialsubgroup',
            options={'ordering': ('name',), 'verbose_name': 'Суб группа материалов', 'verbose_name_plural': '3. Суб группы материалов'},
        ),
    ]
