# Generated by Django 4.2.3 on 2024-09-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_alter_basecolor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['ral'], 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AddField(
            model_name='productpartmaterials',
            name='preferred',
            field=models.BooleanField(default=False),
        ),
    ]
