# Generated by Django 4.0.10 on 2023-12-20 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_alter_material_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['mid_color', 'ral', 'color']},
        ),
        migrations.RenameField(
            model_name='color',
            old_name='hex',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='midcolor',
            old_name='hex',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='color',
            name='mid_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='material.midcolor'),
        ),
    ]
