# Generated by Django 4.2.3 on 2024-09-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_blendermaterial_ao_num_blendermaterial_mtl_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendermaterial',
            name='aspect_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, verbose_name='Aspect Ratio'),
        ),
    ]
