# Generated by Django 4.0.10 on 2023-12-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_color_options_rename_hex_color_color_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['mid_color', 'ral', 'hex']},
        ),
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='hex',
        ),
        migrations.RenameField(
            model_name='midcolor',
            old_name='color',
            new_name='hex',
        ),
        migrations.AlterField(
            model_name='color',
            name='mid_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.midcolor'),
        ),
    ]
