# Generated by Django 4.0.10 on 2023-12-20 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_alter_color_options_rename_color_color_hex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='midcolor',
            name='hex',
            field=models.CharField(max_length=7),
        ),
    ]
