# Generated by Django 4.2.3 on 2024-10-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_recommendedcombinations_recommendedcombinationsparts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendedcombinationsparts',
            options={'ordering': ('combination', 'part', 'material')},
        ),
    ]
