# Generated by Django 4.0.10 on 2023-12-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_alter_color_hex_alter_midcolor_hex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='col',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='nrm',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
