# Generated by Django 4.2.3 on 2024-10-22 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0007_alter_recommendedcombinationsparts_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendedcombinationsparts',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommended_combinations_part', to='material.productpartmaterials'),
        ),
    ]
