# Generated by Django 4.0.10 on 2023-12-20 12:38

import apps.abstract.fields.fields_image
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_material_refl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='color',
        ),
        migrations.AddField(
            model_name='materialgroups',
            name='type',
            field=models.CharField(choices=[('material', 'material'), ('color', 'color')], default=('material', 'material'), max_length=25),
        ),
        migrations.AlterField(
            model_name='material',
            name='bump',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='bump16',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='col',
            field=apps.abstract.fields.fields_image.DeletableFileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='disp',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='disp16',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='image',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='mtl',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='nrm',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='refl',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='material',
            name='rgh',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
    ]
