# Generated by Django 4.2.3 on 2024-10-28 21:15

import apps.abstract.fields.fields_image
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_alter_recommendedcombinationsparts_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendermaterial',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.color'),
        ),
        migrations.AlterField(
            model_name='blendermaterial',
            name='col',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Color'),
        ),
    ]
