# Generated by Django 4.2.3 on 2024-10-28 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0009_blendermaterial_color_alter_blendermaterial_col'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendermaterial',
            name='copy_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.blendermaterial'),
        ),
    ]
