# Generated by Django 4.0.10 on 2023-12-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_alter_materialgroups_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialgroups',
            name='type',
            field=models.CharField(choices=[('material', 'material'), ('color', 'color')], default='material', max_length=25),
        ),
    ]
