# Generated by Django 4.2.3 on 2024-11-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_blendermaterial_copy_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialsset',
            name='copy_from',
            field=models.ForeignKey(blank=True, help_text='Select a MaterialsSet to copy all its data', null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.materialsset', verbose_name='Copy from'),
        ),
    ]
