# Generated by Django 4.0.10 on 2023-12-20 12:49

import apps.abstract.fields.fields_image
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_alter_materialgroups_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlenderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
                ('col', apps.abstract.fields.fields_image.DeletableFileField(upload_to='')),
                ('nrm', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='')),
                ('bump', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='')),
                ('bump16', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='')),
                ('disp', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='')),
                ('disp16', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='')),
                ('rgh', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='')),
                ('mtl', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='')),
                ('refl', apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='material',
            name='bump',
        ),
        migrations.RemoveField(
            model_name='material',
            name='bump16',
        ),
        migrations.RemoveField(
            model_name='material',
            name='col',
        ),
        migrations.RemoveField(
            model_name='material',
            name='disp',
        ),
        migrations.RemoveField(
            model_name='material',
            name='disp16',
        ),
        migrations.RemoveField(
            model_name='material',
            name='mtl',
        ),
        migrations.RemoveField(
            model_name='material',
            name='nrm',
        ),
        migrations.RemoveField(
            model_name='material',
            name='refl',
        ),
        migrations.RemoveField(
            model_name='material',
            name='rgh',
        ),
        migrations.AddField(
            model_name='material',
            name='name',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='material',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='blender_material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='material.blendermaterial'),
        ),
    ]
