# Generated by Django 4.0.10 on 2023-12-25 18:29

import apps.abstract.fields.fields_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_blendermaterial_remove_material_bump_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blendermaterial',
            old_name='nrm',
            new_name='nrm_dl',
        ),
        migrations.AddField(
            model_name='blendermaterial',
            name='nrm_gx',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to=''),
        ),
    ]
