# Generated by Django 4.2.3 on 2025-01-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_blendermaterial_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialgroups',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена, м2'),
        ),
        migrations.AlterField(
            model_name='materialsubgroup',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Цена, м2'),
        ),
    ]
