# Generated by Django 4.2.3 on 2025-02-13 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_alter_materialgroups_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='material',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='depth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='store_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='material.manufacturer'),
        ),
    ]
