# Generated by Django 4.0.10 on 2023-12-25 18:33

import apps.abstract.fields.fields_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0013_rename_nrm_blendermaterial_nrm_dl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blendermaterial',
            name='nrm_dl',
        ),
        migrations.RemoveField(
            model_name='blendermaterial',
            name='nrm_gx',
        ),
        migrations.AddField(
            model_name='blendermaterial',
            name='nrm_dx',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Norma DL'),
        ),
        migrations.AddField(
            model_name='blendermaterial',
            name='nrm_gl',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Norma GX'),
        ),
        migrations.AlterField(
            model_name='blendermaterial',
            name='bump',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Bump'),
        ),
        migrations.AlterField(
            model_name='blendermaterial',
            name='bump16',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Bump 16 bit'),
        ),
        migrations.AlterField(
            model_name='blendermaterial',
            name='col',
            field=apps.abstract.fields.fields_image.DeletableFileField(upload_to='', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='blendermaterial',
            name='disp',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Displacement'),
        ),
        migrations.AlterField(
            model_name='blendermaterial',
            name='disp16',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Displacement 16 bit'),
        ),
        migrations.AlterField(
            model_name='blendermaterial',
            name='mtl',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Metalness'),
        ),
        migrations.AlterField(
            model_name='blendermaterial',
            name='refl',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Reflection'),
        ),
        migrations.AlterField(
            model_name='blendermaterial',
            name='rgh',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Roughness'),
        ),
    ]
