# Generated by Django 4.2.3 on 2025-02-13 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_manufacturer_material_code_material_depth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpartmaterials',
            options={'ordering': ['material']},
        ),
        migrations.RemoveField(
            model_name='productpartmaterials',
            name='color',
        ),
        migrations.RemoveField(
            model_name='productpartmaterialsgroups',
            name='add_palette',
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='material.color'),
        ),
        migrations.AddField(
            model_name='material',
            name='sheet_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена, лист'),
        ),
        migrations.AddField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('material', 'material'), ('color', 'color')], default='material', max_length=25),
        ),
    ]
