# Generated by Django 4.0.10 on 2023-12-25 19:24

import apps.abstract.fields.fields_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0014_remove_blendermaterial_nrm_dl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blendermaterial',
            name='nrm_dx',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Norma DX'),
        ),
        migrations.AlterField(
            model_name='blendermaterial',
            name='nrm_gl',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Norma GL'),
        ),
    ]
