# Generated by Django 4.0.10 on 2023-12-25 19:41

import apps.abstract.fields.fields_image
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0015_alter_blendermaterial_nrm_dx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blendermaterial',
            name='ao',
            field=apps.abstract.fields.fields_image.DeletableFileField(blank=True, null=True, upload_to='', verbose_name='Ambient Occlusion'),
        ),
    ]
