# Generated by Django 4.2.3 on 2025-02-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0016_remove_material_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Цена, м2'),
        ),
        migrations.AlterField(
            model_name='material',
            name='sheet_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, verbose_name='Цена, лист'),
        ),
    ]
