# Generated by Django 4.0.10 on 2023-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0016_blendermaterial_ao'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена, м2'),
        ),
        migrations.AddField(
            model_name='materialgroups',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена, м2'),
        ),
        migrations.AddField(
            model_name='materialsubgroup',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Цена, м2'),
        ),
    ]
