# Generated by Django 4.2.3 on 2025-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0017_alter_material_price_alter_material_sheet_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpart',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='productpart',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
