# Generated by Django 4.0.10 on 2023-12-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0018_materialsubgroup_price_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialsubgroup',
            name='price_level',
        ),
        migrations.AddField(
            model_name='materialgroups',
            name='price_level',
            field=models.CharField(blank=True, choices=[('group', 'Цена на группу'), ('sub_group', 'Цена на суб группу'), ('material', 'Цена на материал')], max_length=9, null=True),
        ),
    ]
