# Generated by Django 4.2.3 on 2025-02-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0018_productpart_slug_alter_productpart_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialgroups',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='materialsubgroup',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='materialgroups',
            name='name',
            field=models.CharField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='materialsubgroup',
            name='name',
            field=models.CharField(max_length=1024),
        ),
    ]
