# Generated by Django 4.2.3 on 2025-03-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0019_materialgroups_slug_materialsubgroup_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialgroups',
            name='color_only',
            field=models.BooleanField(default=False),
        ),
    ]
