# Generated by Django 4.0.10 on 2023-12-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0019_remove_materialsubgroup_price_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='color',
            name='ral',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
