# Generated by Django 4.0.10 on 2023-12-26 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0020_alter_color_options_alter_color_ral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='rgb',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
