# Generated by Django 4.2.3 on 2025-03-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0020_materialgroups_color_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpartmaterialsgroups',
            name='load_all_materials',
            field=models.BooleanField(default=False),
        ),
    ]
