# Generated by Django 4.0.10 on 2023-12-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0022_palette_palettecolor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='palettecolor',
            unique_together={('palette', 'color')},
        ),
    ]
