# Generated by Django 4.0.10 on 2023-12-26 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0023_alter_palettecolor_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palettecolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='palettes', to='material.color'),
        ),
        migrations.AlterField(
            model_name='palettecolor',
            name='palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='material.palette'),
        ),
    ]
