# Generated by Django 4.0.10 on 2023-12-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0024_alter_palettecolor_color_alter_palettecolor_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='lvl',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
