# Generated by Django 4.0.10 on 2023-12-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0025_color_lvl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ['lvl']},
        ),
    ]
