# Generated by Django 4.0.10 on 2023-12-30 22:14

import apps.abstract.fields.fields_image
from django.db import migrations
import project.storage


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0026_alter_color_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='image',
            field=apps.abstract.fields.fields_image.DeletableImageField(blank=True, null=True, storage=project.storage.S3Storage, upload_to=''),
        ),
    ]
