# Generated by Django 4.0.10 on 2024-01-04 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0027_alter_material_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='blender_material',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material', to='material.blendermaterial'),
        ),
    ]
